version: "3.7"

services:
  api:
    build: ./api
    command: air -c .air.toml
    volumes:
      - ./api/:/usr/app
      - ./api/:/go/src/my_library_app
      - ./api/:/usr/local/go/src/my_library_app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    links:
      - mongodb
    environment:
      PORT: 5000
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: rootpassword
      MONGODB_URL: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: my_library_app
    depends_on:
      - mongodb
    networks:
      - mongodb-compose-network
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: my_library_app
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongodb-compose-network

volumes:
  mongodb_data_container:

networks:
  mongodb-compose-network:
      driver: bridge
